Add safety to syncdeletes to prevent dataloss

diff --git a/acdtools b/acdtools
--- a/acdtools
+++ b/acdtools
@@ -171,25 +171,31 @@ function ACDToolsSyncDeletes {
         ENCNAME=$(encfsctl encode --extpass="echo ${ENCFSPASS}" \
             ${ACDMOUNT} "${FILENAME}")
 
-        ACDEXIST=$(${ACDCLI} ls ${ACDSUBDIR}/${ENCNAME} > /dev/null 2>&1; \
-            echo $?)
-        if [ "${ACDEXIST}" -eq "0" ]; then
-            # File does exist, delete it from Amazon Drive
-            ACDToolsLog info "${file} exists on Amazon Drive - deleting"
-            until `${ACDCLI} rm ${ACDSUBDIR}/${ENCNAME}`
-            do
-                # Failed delete - sleep and retry
-                ACDToolsLog error "Delete failed, trying again in 30 seconds"
-                sleep 30
-            done
+        if [ "${#ENCNAME}" -gt "0" ]; then
+            ACDEXIST=$(${ACDCLI} ls ${ACDSUBDIR}/${ENCNAME} > /dev/null 2>&1; \
+                echo $?)
 
-            ACDToolsLog info "${FILENAME} deleted from Amazon Drive"
+            if [ "${ACDEXIST}" -eq "0" ]; then
+                # File does exist, delete it from Amazon Drive
+                ACDToolsLog info "${file} exists on Amazon Drive - deleting"
+                until `${ACDCLI} rm "${ACDSUBDIR}/${ENCNAME}"`
+                do
+                    # Failed delete - sleep and retry
+                    ACDToolsLog error "Delete failed, trying again in 30 \
+                        seconds"
+                    sleep 30
+                done
+
+                ACDToolsLog info "${FILENAME} deleted from Amazon Drive"
+            else
+                ACDToolsLog info "${file} is not on Amazon Drive"
+            fi
+
+            # Remove the UnionFS hidden object
+            rm -rf "${file}"
         else
-            ACDToolsLog info "${file} is not on Amazon Drive"
+            ACDToolsLog error "Empty name returned from encfsctl - skipping."
         fi
-
-        # Remove the UnionFS hidden object
-        rm -rf ${file}
 
     done
 
@@ -197,7 +203,7 @@ function ACDToolsSyncDeletes {
     ACDToolsSyncNodes
 
     # Delete the searchdir so that it is not uploaded as an empty directories
-    rm -rf ${SEARCHDIR}
+    rm -rf "${SEARCHDIR}"
 }
 
 # Upload local data to Amazon Drive
